// Shared bottom-sheet modal styles used across customer & member portal screens
import { StyleSheet } from "react-native";
import { COLORS, FONTS, SIZES, SHADOWS } from "../../utils/constants";

const M = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  box: {
    backgroundColor: COLORS.bg,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    padding: SIZES.xl,
    maxHeight: "88%",
    ...SHADOWS.lg,
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: SIZES.textLg,
    color: COLORS.textPrimary,
    marginBottom: SIZES.lg,
    letterSpacing: -0.2,
  },
  label: {
    fontFamily: FONTS.semibold,
    fontSize: SIZES.textSm,
    color: COLORS.textSecondary,
    marginBottom: 6,
    marginTop: SIZES.sm,
  },
  picker: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.bgCard,
    borderRadius: SIZES.radiusLg,
    padding: SIZES.md,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    marginBottom: SIZES.sm,
    minHeight: 52,
  },
  pickerVal: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: SIZES.textSm,
    color: COLORS.textPrimary,
  },
  pickerPH: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: SIZES.textSm,
    color: COLORS.textMuted,
  },
  noteInput: {
    backgroundColor: COLORS.bgCard,
    borderRadius: SIZES.radiusLg,
    padding: SIZES.md,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    fontFamily: FONTS.regular,
    fontSize: SIZES.textSm,
    color: COLORS.textPrimary,
    height: 88,
    textAlignVertical: "top",
    marginBottom: SIZES.lg,
  },
  fieldInput: {
    backgroundColor: COLORS.bgCard,
    borderRadius: SIZES.radiusMd,
    paddingHorizontal: SIZES.md,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    fontFamily: FONTS.regular,
    fontSize: SIZES.textSm,
    color: COLORS.textPrimary,
  },
  btns: { flexDirection: "row", gap: SIZES.sm, marginTop: SIZES.sm },
  cancelBtn: {
    flex: 1,
    padding: 13,
    borderRadius: SIZES.radiusFull,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    backgroundColor: COLORS.bgCard,
  },
  cancelTxt: {
    fontFamily: FONTS.semibold,
    fontSize: SIZES.textBase,
    color: COLORS.textSecondary,
  },
  confirmBtn: {
    flex: 2,
    padding: 13,
    borderRadius: SIZES.radiusFull,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    ...SHADOWS.sm,
  },
  confirmTxt: {
    fontFamily: FONTS.bold,
    fontSize: SIZES.textBase,
    color: COLORS.white,
  },
  vitem: {
    flexDirection: "row",
    alignItems: "center",
    padding: SIZES.md,
    borderRadius: SIZES.radiusLg,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    marginBottom: SIZES.sm,
    backgroundColor: COLORS.bgCard,
  },
  vitemOn: { borderColor: COLORS.primary, backgroundColor: COLORS.primary + "10" },
});

export default M;
